from karel.stanfordkarel import *

"""
File: ExtensionKarel.py
-----------------------
This file is for optional extension programs. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~STANFORD UNIVERSITY LOGO~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
"""

def main():
    move()
    move()
    move()
    move()
    move()
    move()
    for i in range(8):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    for i in range(10):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    for i in range(12):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    move()
    move()
    move()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    move()
    move()
    move()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    move()
    move()
    move()
    turn_left()
    turn_left()
    for i in range(10):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    for i in range(10):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    move()
    for i in range(10):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    move()
    move()
    move()
    turn_left()
    turn_left()
    for i in range(4):
        paint_corner(RED)
        move()
    move()
    move()
    move()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    move()
    move()
    move()
    move()
    for i in range(4):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    for i in range(12):
        paint_corner(RED)
        move()
    turn_left()
    move()
    turn_left()
    move()
    move()
    for i in range(10):
        paint_corner(RED)
        move()
    turn_right()
    move()
    turn_right()
    move()
    move()
    for i in range(8):
        paint_corner(RED)
        move()

    turn_left()
    turn_left()
    move()
    move()
    move()
    move()
    paint_corner(GREEN)
    move()
    turn_left()
    move() 
    paint_corner(GREEN)
    turn_left()
    move() 
    paint_corner(GREEN)
    move() 
    paint_corner(GREEN)
    turn_right()
    move()
    turn_right()
    move()
    paint_corner(GREEN)
    move()
    turn_left()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    turn_right()
    move()
    turn_right()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    turn_left()
    move()
    turn_left()
    move()
    move()
    paint_corner(GREEN)
    move()
    turn_right()
    move()
    turn_right()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    turn_left()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    turn_right()
    move()
    turn_right()
    move()
    move()
    paint_corner(GREEN)
    move()
    turn_left()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    turn_right()
    move()
    turn_right()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    
    turn_left()
    move()
    turn_left()
    move()
    move()
    paint_corner(GREEN)
    move()
    move()
    turn_right()
    move()
    turn_right()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    turn_left()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    turn_right()
    move()
    turn_right()
    move()
    move()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    turn_right()
    move()
    turn_left()
    move()
    turn_left()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)
    move()
    paint_corner(GREEN)

def turn_right():
    turn_left()
    turn_left()
    turn_left()

if __name__ == "__main__":
    run_karel_program()